// Intrinsic sizes of existing local catalogue assets. CSS still controls their display.
export const imageDimensions: Record<string, { width: number; height: number }> = {
  '/hero/printing-branding.webp': { width: 1024, height: 1024 },
  '/products/black-vehicle-branding.webp': { width: 1080, height: 499 },
  '/products/blue-vehicle-branding.webp': { width: 1080, height: 513 },
  '/products/branded-carry-bag.jpg': { width: 591, height: 442 },
  '/products/branded-coveralls.jpg': { width: 564, height: 543 },
  '/products/branded-drinkware.webp': { width: 552, height: 702 },
  '/products/branded-gazebo.webp': { width: 835, height: 560 },
  '/products/branded-mugs.jpg': { width: 214, height: 236 },
  '/products/branded-overalls-rack.webp': { width: 1400, height: 933 },
  '/products/colourful-waist-bags.webp': { width: 786, height: 727 },
  '/products/corporate-gift-box.webp': { width: 1400, height: 933 },
  '/products/corporate-gift-selection.webp': { width: 1400, height: 933 },
  '/products/corporate-gift-set.jpg': { width: 654, height: 468 },
  '/products/desk-charging-organiser.webp': { width: 1080, height: 1080 },
  '/products/executive-gift-set.webp': { width: 1000, height: 1000 },
  '/products/feather-flags.webp': { width: 585, height: 845 },
  '/products/gift-hamper.webp': { width: 1400, height: 933 },
  '/products/green-polo.webp': { width: 745, height: 887 },
  '/products/grey-backpack.webp': { width: 800, height: 800 },
  '/products/laptop-sleeve.webp': { width: 1080, height: 946 },
  '/products/mug-gift-set.webp': { width: 1016, height: 1080 },
  '/products/navy-polo.webp': { width: 729, height: 878 },
  '/products/notebook-pouch-set.webp': { width: 800, height: 710 },
  '/products/notebooks-pens.webp': { width: 800, height: 800 },
  '/products/passport-luggage-gift-set.webp': { width: 345, height: 393 },
  '/products/pharmacy-signage.webp': { width: 1080, height: 764 },
  '/products/pink-hoodie.webp': { width: 465, height: 576 },
  '/products/ppe-footwear.jpg': { width: 213, height: 236 },
  '/products/printed-white-tshirt.webp': { width: 880, height: 861 },
  '/products/promotional-pens.webp': { width: 1000, height: 948 },
  '/products/reflective-overalls-range.webp': { width: 933, height: 1400 },
  '/products/round-keyrings.webp': { width: 943, height: 776 },
  '/products/running-armband.webp': { width: 395, height: 594 },
  '/products/tan-travel-organiser.webp': { width: 1080, height: 1080 },
  '/products/tassel-keyrings.webp': { width: 1079, height: 1079 },
  '/products/travel-adapter.webp': { width: 978, height: 1080 },
  '/products/travel-gift-set.webp': { width: 864, height: 1080 },
  '/products/travel-wash-bag.webp': { width: 800, height: 650 },
  '/products/two-tone-travel-organiser.webp': { width: 1080, height: 1080 },
  '/products/wireless-mice.webp': { width: 1080, height: 1004 },
  '/service-crops/business-cards.webp': { width: 495, height: 335 },
  '/service-crops/large-format.webp': { width: 330, height: 96 },
  '/service-crops/ppe-equipment.webp': { width: 416, height: 201 },
  '/service-crops/tshirt.webp': { width: 79, height: 78 },
  '/service-crops/water-bottles.webp': { width: 240, height: 153 },
};

// Only real, generated derivatives are registered. Originals retain their URLs.
export const imageVariants: Record<string, { src: string; width: number }[]> = {
  '/hero/printing-branding.webp': [
    { src: '/hero/printing-branding-640.webp', width: 640 },
  ],
  '/products/tassel-keyrings.webp': [
    { src: '/products/responsive/tassel-keyrings-480.webp', width: 480 },
    { src: '/products/responsive/tassel-keyrings-800.webp', width: 800 },
  ],
  '/products/laptop-sleeve.webp': [
    { src: '/products/responsive/laptop-sleeve-480.webp', width: 480 },
    { src: '/products/responsive/laptop-sleeve-800.webp', width: 800 },
  ],
  '/products/travel-gift-set.webp': [
    { src: '/products/responsive/travel-gift-set-480.webp', width: 480 },
    { src: '/products/responsive/travel-gift-set-800.webp', width: 800 },
  ],
  '/products/promotional-pens.webp': [
    { src: '/products/responsive/promotional-pens-480.webp', width: 480 },
    { src: '/products/responsive/promotional-pens-800.webp', width: 800 },
  ],
};